import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menus = [
  {
    label: "Home",
    href: "/",
    button: false,
  },
  {
    label: "Blog",
    href: "/blog",
    button: false,
  },
  {
    label: "About Us",
    href: "/about-us",
    button: false,
  },

  {
    label: "Contact Us",
    href: "/contact-us",
    button: false,
  },

  {
    label: "Login",
    href: "/login",
    button: false,
  },
  {
    label: "SignUp",
    href: "/signup",
    button: true,
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="px-4 bg-white shadow-lg sticky top-0 left-0 w-full py-6 flex justify-between items-center">
          <Link href={"/"} className="text-2xl font-bold">PrashantBlogs</Link>
          <div className="flex gap-8 items-center">
            {menus.map((item, index) => (
              <Link
                href={item.href}
                key={index}
                className={item.button ? "bg-violet-600 px-8 py-2 rounded-full text-white" : null}
              >
                {item.label}
              </Link>
            ))}
          </div>
        </nav>
        <section className="px-[10%] py-16">{children}</section>
        <footer className="bg-gray-950 h-[25rem] flex  items-center justify-center text-white text-3xl">
        myfooter
        </footer>
      </body>
    </html>
  );
}
